from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"


# declare https://github.com/snakemake-workflows/rna-seq-kallisto-sleuth as a module
module rna_seq_kallisto_sleuth:
    snakefile:
        # "/home/adrian/Documents/Promotion/rna-seq-kallisto-sleuth/workflow/Snakefile"
        # "/homes/aprinz/rna-seq-kallisto-sleuth/workflow/Snakefile"
        # "/home/adrian/Documents/Promotion/rna-seq-kallisto-sleuth/workflow/Snakefile"
        github(
            "snakemake-workflows/rna-seq-kallisto-sleuth",
            path="workflow/Snakefile",
            tag="v2.10.0",
        )
    config:
        config


# use all rules from https://github.com/snakemake-workflows/rna-seq-kallisto-sleuth
use rule * from rna_seq_kallisto_sleuth


# rule all:
#     input:
#         "config/samples.tsv",
#         "config/units.tsv",


rule create_samples:
    input:
        desc="resources/sample_desc.xlsx",
        data="resources/data/",
    output:
        "config/samples.tsv",
    conda:
        "envs/create_tsvs.yaml"
    script:
        "scripts/create_samples.py"


rule create_units:
    input:
        desc="resources/sample_desc.xlsx",
        data="resources/data/",
    output:
        "config/units.tsv",
    conda:
        "envs/create_tsvs.yaml"
    script:
        "scripts/create_units.py"
